apiVersion: apps/v1
kind: Deployment
metadata:
  name: combined-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: combined-service
  template:
    metadata:
      labels:
        app: combined-service
    spec:
      containers:
        - name: combined-service
          image: abhinav932002/combined-service:latest
          ports:
            - containerPort: 8080

---

apiVersion: v1
kind: Service
metadata:
  name: combined-service
spec:
  type: NodePort
  selector:
    app: combined-service
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30003
